### ISSUE TITLE
Ver 3 new error

### ISSUE THREAD

**Issue by limelect** [VoSs2o0o/NetFormat#2]
D10.2.3
[dcc32 Error] VoTools.FStr.pas(95): E2034 Too many actual parameters
[dcc32 Error] VoTools.FStr.pas(131): E2034 Too many actual parameters

**Comment by VoSs2o0o** [comment]
Ohh, i havn't seen it. The Bug was in all Version except of 12.
Should be ok now (V3.0.1)
